name: Deploy Nexus

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Dependencies
        # Esta linha obriga o GitHub a criar as bibliotecas do zero sem o Lock file
        run: npm install --no-package-lock
        
      - name: Build
        # CI=false impede que avisos bobos sejam tratados como erros fatais
        run: CI=false npm run build
        
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
